### ISSUE TITLE
HelpCommand responsibility in solution/java/week05-complexity/exercise2

### ISSUE THREAD

**Issue by d215steinberg** [advent-of-craft/2024-summer-craft-book#1]
I am not crazy about App assuming the responsibility of getting the command names.  What if we need to modify the Help command to print descriptions of the commands as well as their names.  We should be able to accomplish this by modifying only HelpCommand, not App.  Therefore, 
a) CommandProcessor should the commands map (I understand why you don't want to do that -- see below.)
b) App should pass the map to HelpCommand
c) HelpCommand should take what it needs (in this case, the names) from the commands map

Consider wrapping the commands map in a Commands class to avoid exposing the map implementation.

**Comment by ythirion** [comment]
Hi @d215steinberg thanks for sharing your Point Of View.
I don’t know if you are aware about it but we favor contribution, sharing ideas through a dedicated Discord Server available [here](https://discord.gg/E5Z9s9UKTS). Could you join us and share this in a dedicated thread for the given week please? 
It would be valuable for all the participants to open these discussions there 🙏
Thanks a lot for that and see you there 😉
